apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - 99d
  restartPolicy: Never
  tolerations:
  - effect: NoExecute
    key: service
    operator: Equal
    value: arm