apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
      - sh
      - -c
      - |
        mkdir -p /root/.ssh  && sleep 99d
      volumeMounts:
        - name: m2-home
          mountPath: /home/jenkins/agent/.m2
        - name: ssh-key
          mountPath: /root/.ssh
          readOnly: true
      env:
      - name: GIT_SSH_COMMAND
        value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  restartPolicy: Never
  tolerations:
  - effect: NoExecute
    key: service
    operator: Equal
    value: arm
  volumes:
    - name: m2-home
      persistentVolumeClaim:
        claimName: jenkins-pv-claim-m2
    - name: ssh-key
      secret:
        secretName: gitlab-ssh-key
        defaultMode: 0600