apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: m2-home
          mountPath: /home/jenkins/agent/.m2
  restartPolicy: Never
  tolerations:
  - effect: NoExecute
    key: service
    operator: Equal
    value: arm
  volumes:
    - name: m2-home
      persistentVolumeClaim:
        claimName: jenkins-pv-claim-m2