apiVersion: v1
kind: Pod
metadata:
  name: compiler
spec:
  containers:
  - name: compiler
    image: 526418118390.dkr.ecr.ap-southeast-1.amazonaws.com/shareit-csp/jenkins:compile_x86
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: ssh-key
      mountPath: /root/.ssh
      readOnly: true
    env:
    - name: GIT_SSH_COMMAND
      value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  volumes:
  - name: workspace
    emptyDir: {}
  - name: ssh-key
    secret:
      secretName: gitlab-ssh-key
      defaultMode: 0600
  restartPolicy: Never